#!/usr/bin/python
# --------------------------------------------------------------------------------------------------
# Example function code—stopping EC2 instances
# --------------------------------------------------------------------------------------------------
import boto3
region = 'us-west-1'
instances = ['i-12345cb6de4f78g9h', 'i-08ce9b2d7eccf6d26']
ec2 = boto3.client('ec2', region_name=region)

def lambda_handler(event, context):
    ec2.stop_instances(InstanceIds=instances)
    print('stopped your instances: ' + str(instances))
# --------------------------------------------------------------------------------------------------
# Important: For region, replace "us-west-1" with the AWS Region that your instances are in. 
# For instances, replace the example EC2 instance IDs with the IDs of the specific instances that you want to stop and start.
 
# Example function code—starting EC2 instances
# --------------------------------------------------------------------------------------------------
import boto3
region = 'us-west-1'
instances = ['i-12345cb6de4f78g9h', 'i-08ce9b2d7eccf6d26']
ec2 = boto3.client('ec2', region_name=region)

def lambda_handler(event, context):
    ec2.start_instances(InstanceIds=instances)
    print('started your instances: ' + str(instances))
# --------------------------------------------------------------------------------------------------
# Important: For region and instances , use the same values that you used for the code to stop your EC2 instances.
